# This is an appspec.yml template file for use with an EC2/On-Premises deployment in AWS CodeDeploy.
# The lines in this template starting with the hashtag symbol are
#   instructional comments and can be safely left in the file or
#   ignored.
# For help completing this file, see the "AppSpec File Reference" in the
#   "AWS CodeDeploy User Guide" at
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
# Specify "os: linux" if this revision targets Amazon Linux,
#   Red Hat Enterprise Linux (RHEL), or Ubuntu Server
#   instances.
# Specify "os: windows" if this revision targets Windows Server instances.
# (You cannot specify both "os: linux" and "os: windows".)
os: linux

files:
  - source: /config
    destination: /home/es-config
  - source: /scripts
    destination: /home/scripts
    
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
    - location: scripts/nginx.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/get_stack_output.sh
      timeout: 300
      runas: root
    - location: scripts/read_replace.py
      timeout: 300
      runas: root
    - location: scripts/place_conf.sh
      timeout: 300
      runas: root

